Guide
bitfinexcom/bfx-hf-ui pull request #179
Opened 2020-08-31 12:00 UTC by AntonNazarenko

2020-09-09 10:12 UTC, robertkowalski commented
it does not start:

```
Compiled with warnings.

./src/ui/Markdown/index.js
  Line 3:40:   Extra semicolon                                     semi
  Line 4:45:   Extra semicolon                                     semi
  Line 23:47:  Extra semicolon                                     semi
  Line 29:43:  Extra semicolon                                     semi
  Line 53:11:  Dangerous property 'dangerouslySetInnerHTML' found  react/no-danger

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

2020-09-09 10:13 UTC, robertkowalski commented
had to rebase your PR against latest master

2020-09-09 10:17 UTC, robertkowalski commented
after closing the guide in the middle there is a border around the element, can we remove it?

![Screen Shot 2020-09-09 at 12 16 08](https://user-images.githubusercontent.com/298166/92586324-6020cd00-f296-11ea-8628-6957f8eb3f7c.png)

2020-09-09 10:18 UTC, robertkowalski commented
Can we rename "Last" to "Finish" in the last step? Because clicking on "Last" closes the guide.

2020-09-09 10:19 UTC, robertkowalski commented
![Screen Shot 2020-09-09 at 12 19 10](https://user-images.githubusercontent.com/298166/92586567-afff9400-f296-11ea-9528-cc55a02e2bbd.png)

2020-09-09 10:20 UTC, robertkowalski commented on src/pages/StrategyEditor/StrategyEditor.js
> +        content: 'Or open existing one.',
`Or open an existing one`

2020-09-09 10:20 UTC, robertkowalski commented on src/pages/StrategyEditor/StrategyEditor.js
> +        content: 'here you can find all documentation you need, to code yourn own strategies.',
`yourn ` -> `your`

2020-09-09 10:21 UTC, robertkowalski commented on src/pages/StrategyEditor/StrategyEditor.js
> +        content: 'here you can find all documentation you need, to code yourn own strategies.',
is this text final?

Maybe we can go with: `In this section you find the available function declarations to code your own strategies`

2020-09-09 10:25 UTC, robertkowalski commented on src/pages/Settings/Settings.js
> +          content: 'After all steps press this button, to update your settings.',
not sure if we need a guide for this, those sections should be self-explanatory, right? 

i.e. `With this button you can enable/disable DMS switch.` does not provide much worth to the user

Maybe remove the guide from this page, and if required add some more context to the UI fields, example:

![Screen Shot 2020-09-09 at 12 25 02](https://user-images.githubusercontent.com/298166/92587141-87c46500-f297-11ea-8105-3d0a81db3c81.png)

2020-09-09 10:28 UTC, robertkowalski commented on src/pages/Settings/Settings.js
> +          content: 'After all steps press this button, to update your settings.',
![Screen Shot 2020-09-09 at 12 27 44](https://user-images.githubusercontent.com/298166/92587402-e4c01b00-f297-11ea-933c-74f6caa9c7f9.png)

2020-09-09 10:28 UTC, robertkowalski commented on src/pages/Settings/Settings.js
> +          content: 'After all steps press this button, to update your settings.',
That could be done in a next PR...

2020-09-09 10:29 UTC, robertkowalski commented on src/components/GridLayoutPage/GridLayoutPage.js
> +        content: 'Create new component.',
maybe removing the `.` makes sense? for the guide-bubbles it looks nicer without the fullstop

2020-09-09 10:30 UTC, robertkowalski commented on src/pages/Trading/Trading.js
> +        content: 'You can save your layout, after you have customized it.',
`You can save your layout after you have customized it`

2020-09-09 10:30 UTC, robertkowalski commented on src/pages/Trading/Trading.js
> +        content: 'By clicking on this button you can add a new components to this page.',
`component`

2020-09-09 10:33 UTC, robertkowalski commented on src/pages/Trading/Trading.js
> +        content: 'Version of your app, there will be "Update" button, if you are running old version.',
`Here you can find the current version of your app, in case there is an update, there will be an update button`

2020-09-09 12:25 UTC, robertkowalski requested changes
good work, some changes required though

2020-09-10 15:06 UTC, robertkowalski commented
in the beginning the icon has an ugly border always:

![Screen Shot 2020-09-10 at 17 05 51](https://user-images.githubusercontent.com/298166/92751071-f54fbe80-f387-11ea-8079-076779e76738.png)

2020-09-10 15:07 UTC, robertkowalski commented
![Screen Shot 2020-09-10 at 17 06 56](https://user-images.githubusercontent.com/298166/92751188-0d274280-f388-11ea-966f-84385d6f8bb8.png)


`Last (3/3)` should be named `Finish`

2020-09-11 13:26 UTC, robertkowalski commented
there are still issues with theborders in 3 cases, would be good to remove them all, created a video of them

2020-09-29 08:54 UTC, robertkowalski commented
![Screen Shot 2020-09-29 at 10 53 38](https://user-images.githubusercontent.com/298166/94535651-1ba7a200-0242-11eb-9f6e-af5045ce235f.png)

2020-09-29 08:54 UTC, robertkowalski commented
![Screen Shot 2020-09-29 at 10 53 28](https://user-images.githubusercontent.com/298166/94535667-1fd3bf80-0242-11eb-9548-5117a9a00bbd.png)

2020-09-29 08:54 UTC, robertkowalski commented
the issues are still there.

2020-09-29 09:14 UTC, AntonNazarenko commented
@robertkowalski @prdn I've removed this outline from the entire app just checked it in chrome and electron app. Maybe you didn't pull the changes?

2020-09-29 09:15 UTC, AntonNazarenko commented
<img width="406" alt="Снимок экрана 2020-09-29 в 12 13 43" src="https://user-images.githubusercontent.com/51406639/94539036-68dd4100-024d-11eb-8fc0-15b1fc5387cf.png">
<img width="103" alt="Снимок экрана 2020-09-29 в 12 13 54" src="https://user-images.githubusercontent.com/51406639/94539042-6b3f9b00-024d-11eb-853a-a9af855f09ec.png">
that's how it looks in the electron app

2020-09-29 09:19 UTC, robertkowalski commented
rechecking. i can confirm its fixed, had to rebuild the css

2020-09-29 09:21 UTC, robertkowalski approved these changes
lgtm, will change the texts after merge

2020-09-29 09:35 UTC, merged