fix react errors
bitfinexcom/bfx-hf-ui pull request #193
Opened 2020-10-01 18:15 UTC by AntonNazarenko

fixed unique keys error, and all other console erros

2020-10-01 18:25 UTC, robertkowalski commented on src/ui/Input/Input.js
> +            placeholder={this.isPlaceholderValid(placeholder) ? placeholder : 'undefined'}
undefined as a string?

2020-10-01 18:25 UTC, robertkowalski commented on src/ui/Input/Input.js
> +          placeholder={this.isPlaceholderValid(placeholder) ? placeholder : 'undefined'}
same here, you probably want to pass the object

2020-10-01 18:40 UTC, AntonNazarenko commented on src/ui/Input/Input.js
> +          placeholder={this.isPlaceholderValid(placeholder) ? placeholder : 'undefined'}
@robertkowalski updated.

2020-10-01 18:42 UTC, robertkowalski commented on src/ui/Panel/index.js
> -                  key={tab.props.htmlKey || tab.props.tabTitle}
we can remove `hmtlKey` from the props file: `Panel.props.js`

2020-10-01 18:46 UTC, robertkowalski commented on src/ui/Panel/index.js
> +                  key={tab.props.tabtitle}
are you sure this works with the react elements passed in the TradeStatePanel? Thats the reason why I added htmlKey. Now I get this after login, our old error:

![Screen Shot 2020-10-01 at 20 44 36](https://user-images.githubusercontent.com/298166/94850361-21121180-0427-11eb-8fb1-ba63e32b9a96.png)

2020-10-01 18:49 UTC, robertkowalski requested changes
the old `[Object object]` issue on the Trading Terminal page is back. It was fixed by the `htmlKey` addition before

2020-10-01 18:50 UTC, AntonNazarenko commented on src/ui/Panel/index.js
> +                  key={tab.props.tabtitle}
sry, just incorrect merge, I didn't want to delete this, thanks for noticing

2020-10-01 18:53 UTC, AntonNazarenko commented on src/ui/Panel/index.js
> +                  key={tab.props.tabtitle}
updated

2020-10-02 10:06 UTC, robertkowalski approved these changes
lgtm

2020-10-02 10:57 UTC, merged