fix trading state panel
bitfinexcom/bfx-hf-ui pull request #198
Opened 2020-10-05 19:25 UTC by AntonNazarenko

Fixed: 
- live algo order rendering
- live atomic order rendering
- live algo order deletion 
- live atomic order deletion
- navbar bugs

2020-10-07 14:24 UTC, robertkowalski requested changes
good work, small issue

2020-10-07 14:24 UTC, robertkowalski commented on src/ui/Panel/index.js
> +                  className={ClassNames({ active: tab.props.htmlKey === selectedTab.props.htmlKey })}
hmmmm...

that requires that all usages of the `<Panel>` provide a `htmlKey`, so far this is just done on the `TradesPanel` because there react elements are passed into the tabtitle prop of the Panel

2020-10-07 14:24 UTC, robertkowalski commented on src/ui/Panel/index.js
> +                  className={ClassNames({ active: tab.props.htmlKey === selectedTab.props.htmlKey })}
hmm i just checked and keeping this like it is would not break anything. so just revert this part?

2020-10-07 14:26 UTC, robertkowalski commented on src/components/TradingStatePanel/TradingStatePanel.js
> +            htmlKey='Balances'
just required for html passed into the tabtitle prop, here it is just `tabtitle='Balances'`

2020-10-07 15:57 UTC, AntonNazarenko commented on src/ui/Panel/index.js
> +                  className={ClassNames({ active: tab.props.htmlKey === selectedTab.props.htmlKey })}
@robertkowalski navigation doesn't work correctly when we are comparing tabtitles, which can be any value ( string or object ). For example, you can try to submit algo order, when you have algo order tab opened in the trading state panel, after submitting an AO, you should see, that your active page has changed, but when we are comparing htmlKeys, then everything works well. I think, that comparing two strings it's a better approach than comparing react child's. What do you think about this?

2020-10-12 13:28 UTC, robertkowalski commented on src/ui/Panel/index.js
> +                  className={ClassNames({ active: tab.props.htmlKey === selectedTab.props.htmlKey })}
good point, i was hoping for some react-internal magic to happen

2020-10-12 13:33 UTC, robertkowalski commented on src/ui/Panel/index.js
> +                  className={ClassNames({ active: tab.props.htmlKey === selectedTab.props.htmlKey })}
what is with other usages of <Panel> ? E.g. in the StrategyEditor? Do we have to fix them?

2020-10-12 14:15 UTC, robertkowalski commented on src/ui/Panel/index.js
> +                  className={ClassNames({ active: tab.props.htmlKey === selectedTab.props.htmlKey })}
confirmed, it breaks the other tab elements without htmlKey.

how about this softmigration?

inside the panel you do (pseudocode here, best to put into a separate method):

```js

if (typeof selectedTab.props.tabtitle ==='string') {
  // take string
} else {
  if (!htmlKey) console.trace('htmlKey missing')
  // take html key
}


```

2020-10-12 14:15 UTC, robertkowalski requested changes
https://github.com/bitfinexcom/bfx-hf-ui/pull/198#discussion_r503325750

2020-10-13 10:37 UTC, robertkowalski approved these changes
LGTM

2020-10-13 10:57 UTC, merged