chart panel & ui middleware
bitfinexcom/bfx-hf-ui pull request #203
Opened 2020-10-12 16:10 UTC by AntonNazarenko

2020-10-12 16:32 UTC, robertkowalski commented on src/redux/middleware/ui/index.js
> +        store.dispatch(WSActions.recvNotification({
it reads a bit strange to use a websocket action for local notifciations

2020-10-12 16:33 UTC, robertkowalski commented on src/redux/middleware/ui/index.js
> +        store.dispatch(WSActions.recvNotification({
do we have a local alternative?

2020-10-12 16:36 UTC, AntonNazarenko commented on src/redux/middleware/ui/index.js
> +        store.dispatch(WSActions.recvNotification({
no, I can create it if needed, it would be doing the same thing, but it would be more clear for developers

2020-10-12 16:37 UTC, robertkowalski commented
after building the css i get a lot of white bars

![Screen Shot 2020-10-12 at 18 36 14](https://user-images.githubusercontent.com/298166/95770588-ee370b80-0cb9-11eb-8434-48d476c96810.png)

2020-10-12 16:39 UTC, robertkowalski commented on src/redux/middleware/ui/index.js
> +        store.dispatch(WSActions.recvNotification({
if we don't refactoring it to be a `ui` action would make sense i guess... `recvNotification` has not many usages, so should be a quick change...

2020-10-12 16:41 UTC, robertkowalski commented
the fields over the chart changed.

current:
![Screen Shot 2020-10-12 at 18 40 23](https://user-images.githubusercontent.com/298166/95770911-70bfcb00-0cba-11eb-9c03-53e62f90ad5f.png)


new:
![Screen Shot 2020-10-12 at 18 37 29](https://user-images.githubusercontent.com/298166/95770688-132b7e80-0cba-11eb-87d0-da4d2f45bd9f.png)

2020-10-12 16:41 UTC, robertkowalski requested changes
this needs some fine tuning and fixes

2020-10-12 17:16 UTC, robertkowalski commented
field issue fixed by rebase

2020-10-13 08:11 UTC, robertkowalski commented on src/redux/reducers/notifications/index.js
> +      console.log(notification)
debug?

2020-10-13 09:23 UTC, robertkowalski approved these changes
lgtm

2020-10-13 09:36 UTC, merged