add favorite trading pair
bitfinexcom/bfx-hf-ui pull request #266
Opened 2021-01-17 22:36 UTC by AntonNazarenko

Added ability to choose your favorite pairs
After a user selected the favorite pairs they will be shown in the Favorite Trading Pairs section
Also a user able to delete a favorite trading pair just by clicking on the star

2021-01-18 10:54 UTC, avsek477 commented
lgtm

2021-01-18 11:18 UTC, robertkowalski commented on src/ui/Select/Select.js
> +const customOption = ({ innerProps, children, data }, onFavoriteSelect, favoritePairs) => {
```
Failed to compile.

./src/ui/Select/Select.js
  Line 8:25:  'innerProps' is missing in props validation  react/prop-types
  Line 8:37:  'children' is missing in props validation    react/prop-types
  Line 8:47:  'data' is missing in props validation        react/prop-types
  Line 9:11:  'data.value' is missing in props validation  react/prop-types

Search for the keywords to learn more about each error.
```

2021-01-18 11:18 UTC, robertkowalski commented on src/ui/Select/Select.js
> +const customOption = ({ innerProps, children, data }, onFavoriteSelect, favoritePairs) => {
read the thread with abishekd, maybe try to rebase with current master

2021-01-18 11:22 UTC, robertkowalski commented on src/components/FavoriteTradingPairs/index.js
> +          <div className='hfui-favoritepair__content empty'>Empty</div>
better: `No Favorites starred yet`

2021-01-18 11:44 UTC, robertkowalski requested changes
nice work! after fixing the linting errors we can merge.

note: merge requires a package bump for bfx-api-models

2021-01-18 15:08 UTC, robertkowalski commented
linter is happy now, can you fix https://github.com/bitfinexcom/bfx-hf-ui/pull/266#discussion_r559496647 with the improved wording? thanks!

2021-01-18 15:10 UTC, robertkowalski requested changes
linter is happy now, can you fix the remaining issue with the improved wording?

https://github.com/bitfinexcom/bfx-hf-ui/pull/266/files#r559496647

2021-01-19 15:42 UTC, robertkowalski approved these changes
lgtm

2021-01-19 16:26 UTC, merged