[WIP] Add algo orders tooltips
bitfinexcom/bfx-hf-ui pull request #268
Opened 2021-01-19 11:13 UTC by alexstotsky

### PR description
- Added tooltips for algo orders
- Full description https://app.asana.com/0/1125859137800433/1199410579198853

<img width="699" alt="algo-tooltip" src="https://user-images.githubusercontent.com/41899906/105027073-fe4c4d00-5a57-11eb-8b61-7ff407013869.png">

2021-01-19 12:07 UTC, robertkowalski commented on package-lock.json
> +          "version": "git+http://github.com/bitfinexcom/bfx-api-node-models.git#374d9b9850119dc1447df876c01b597cc8f260d3",
this downgrades the node model lib, not related to this PR

2021-01-19 12:20 UTC, robertkowalski commented on src/components/OrderForm/FieldComponents/input.number.js
> +            </Tooltip>
it seems that some inputs have no help text.

what do you think about adding an icon like `( i )` to those input labels where we offer additional help? then on hover of those icons the tooltip is shown..

2021-01-19 12:21 UTC, robertkowalski requested changes
nice work!

from a usability side its not clear which inputs offer additional help, so i keep moving my mouse over some of them with no result.

how about indicating inputs with help through a small info-icon that people can hover over?

2021-01-19 13:38 UTC, alexstotsky commented on package-lock.json
> +          "version": "git+http://github.com/bitfinexcom/bfx-api-node-models.git#374d9b9850119dc1447df876c01b597cc8f260d3",
reverted this change

2021-01-19 16:45 UTC, alexstotsky commented on src/components/OrderForm/FieldComponents/input.number.js
> +            </Tooltip>
it's a great idea I think 
reworked the way you proposed

2021-01-29 10:58 UTC, robertkowalski commented on src/index.scss
> +@import '~react-popper-tooltip/dist/styles';
```
rm -rf node_modules && npm i && npm run build-css
```

```
Wrote CSS to /Users/robert/bitfinex/bfx-hf-ui/src/components/UnlockOrderFormModal/style.css
{
  "status": 1,
  "file": "/Users/robert/bitfinex/bfx-hf-ui/src/index.scss",
  "line": 9,
  "column": 9,
  "message": "returned value of `file` must be a string",
  "formatted": "Error: returned value of `file` must be a string\n        on line 9 of src/index.scss\n>> @import '~react-popper-tooltip/dist/styles';\n\n   --------^\n"
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bfx-hf-ui@3.4.0 build-css: `cross-env node-sass-chokidar src/ -o src/ --importer=node_modules/node-sass-tilde-importer`
```

2021-01-29 17:31 UTC, alexstotsky commented on src/index.scss
> +@import '~react-popper-tooltip/dist/styles';
can’t reproduce this issue
all packages installed successfully
and styles compiles with no problem

could you please try once again and confirm
that problem still present on your side?

2021-02-01 10:48 UTC, AntonNazarenko commented on src/index.scss
> +@import '~react-popper-tooltip/dist/styles';
I've also just tried to reproduce it, but I'm also can't see this issue

2021-02-01 10:55 UTC, xf3rno requested changes
Minor changes, looks good overall. Mainly would be nice to see string rendering for the `customHelp` field alongside `label` in components.

2021-02-01 10:55 UTC, xf3rno commented on src/components/OrderForm/FieldComponents/input.dropdown.js
> +                <i className='fa fa-info-circle' />
It would be nice to have the icon configurable, adding a new key to the AO UI def. Since you are already touching this logic here.

2021-02-01 10:55 UTC, xf3rno commented on src/ui/Tooltip/Tooltip.js
> +  getArrowProps,
I recommend adding defaults for both of these functions, to pass through the default object on line 14 if none is provided.

2021-02-01 10:55 UTC, xf3rno commented on src/ui/Tooltip/Tooltip.js
> +        tooltip={Tooltip(tooltipContent, tooltipClasses)}
It would be slightly more optimal to store the `Tooltip` func res on state derived from props

2021-02-01 10:55 UTC, xf3rno commented on src/ui/Tooltip/Tooltip.js
> +const Trigger = ({
Extra root-level functions like these usually go in a helpers file, in this case `Tooltip.helpers.js`

2021-02-01 10:55 UTC, xf3rno commented on src/ui/Tooltip/Tooltip.js
> +      style: { zIndex: 99999 },
Why not move this into the styles?

2021-02-01 10:55 UTC, xf3rno commented on src/index.scss
> +@import '~react-popper-tooltip/dist/styles';
Also cannot reproduce

2021-02-01 11:09 UTC, robertkowalski approved these changes
lgtm

2021-02-01 15:33 UTC, merged