[WIP] Add market selector to charts
bitfinexcom/bfx-hf-ui pull request #280
Opened 2021-01-29 17:15 UTC by alexstotsky

2021-02-01 15:05 UTC, AntonNazarenko approved these changes
LGTM

2021-02-06 19:53 UTC, xf3rno requested changes
See comments; the chart will update aggressively given the lack of explicit checks in `shouldComponentUpdate`. Nice add otherwise! Great to finally see this in.

2021-02-06 19:53 UTC, xf3rno commented on src/components/ChartPanel/ChartPanel.container.js
> +    dispatch(WSActions.addChannelRequirement(exchange, ['trades', market]))
Could you add a dedicated action here for adding/removing trade channel requirements? Instead of calling `WSActions` directly.

2021-02-06 19:53 UTC, xf3rno commented on src/components/ChartPanel/ChartPanel.container.js
> +      'favourite_trading_pairs.save',
A dedicated action for saving favourite trading pairs would be better here.

2021-02-06 19:53 UTC, xf3rno commented on src/components/ChartPanel/ChartPanel.js
> +    return (!_isEqual(nextProps, this.props) || !_isEqual(nextState, this.state))
This could be better, it's as if no `shouldComponentUpdate` is supplied at all. I recommend you check for the necessary changes in state/props instead.

2021-02-06 19:53 UTC, xf3rno commented on src/ui/Panel/index.js
> +      label,
You should join these lines together to match the repo code style, wrapping at 80 cols.

2021-02-06 21:57 UTC, alexstotsky commented on src/ui/Panel/index.js
> +      label,
placing destructured props from top to bottom is better for code readability

2021-02-08 08:51 UTC, alexstotsky commented on src/components/ChartPanel/ChartPanel.js
> +    return (!_isEqual(nextProps, this.props) || !_isEqual(nextState, this.state))
in the cases of complex and nested props usage of `shouldComponentUpdate` better for performance optimization

in other cases we can just use `PureComponent ` or `React.memo` for functional

2021-02-08 11:54 UTC, alexstotsky commented on src/components/ChartPanel/ChartPanel.container.js
> +    dispatch(WSActions.addChannelRequirement(exchange, ['trades', market]))
I just followed the same pattern that you used all across the app, for consistency - all actions handled via `WSActions` or `UIActions` directly in the containers.

<img width="634" alt="actions" src="https://user-images.githubusercontent.com/41899906/107216151-0115de80-6a15-11eb-8c9c-9de3e2b72e3c.png">

2021-02-08 11:54 UTC, alexstotsky commented on src/components/ChartPanel/ChartPanel.container.js
> +      'favourite_trading_pairs.save',
same as above

2021-02-08 11:57 UTC, alexstotsky commented on src/components/ChartPanel/ChartPanel.container.js
> +    dispatch(WSActions.addChannelRequirement(exchange, ['trades', market]))
But this is a good idea I think, maybe we will refactor all actions across the app with dedicated ones to improve code readability someday.

2021-02-08 13:36 UTC, robertkowalski commented on src/components/ChartPanel/ChartPanel.js
> +  renderExchangeDropdown() {
unused code? we don't support exchange selection and will stay with bitfinex

2021-02-08 13:40 UTC, robertkowalski requested changes
really nice, one small issue, i think multiple exchange selection is not required any more

2021-02-08 17:12 UTC, alexstotsky commented on src/components/ChartPanel/ChartPanel.js
> +  renderExchangeDropdown() {
fixed

2021-02-09 09:27 UTC, robertkowalski approved these changes
lgtm

2021-02-09 09:27 UTC, merged