[WIP] Prevent spam order submitting
bitfinexcom/bfx-hf-ui pull request #285
Opened 2021-02-11 12:36 UTC by alexstotsky

2021-02-15 11:27 UTC, avsek477 commented
lgtm :+1:

2021-02-15 11:44 UTC, avsek477 approved these changes

2021-02-15 11:53 UTC, robertkowalski commented on src/components/OrderForm/OrderForm.container.js
> +
ah, some air <3

2021-02-15 12:05 UTC, robertkowalski commented on src/redux/selectors/notifications/get-latest-notification-ts.js
> +  return _get(state, `${path}.0.mts`, null)
when you `console.log` this you will see that its set very fast, for every order book entry thats coming in...

so we can't reliably use it for determining if an order was submitted / sent

we should wait for an `on` message

2021-02-15 12:07 UTC, robertkowalski requested changes
the updates coming in (trades, orderbook) in a usual setup are too many to reliably use that as a confirmation if an order was sent

that needs some overhaul to make this a reliable feature, but the algo popups def have priority

2021-04-30 12:13 UTC, alexstotsky commented
Ok then, will need to investigate which approach better be used here instead of the current based on notifications. What ways to handle it we currently have and what changes should be added to checking the order processing status in an optimal way. A different approach will be done in separate pr, this one will be closed.

2021-04-30 12:13 UTC, closed without merging