Feature: Autol-login in dev mode
bitfinexcom/bfx-hf-ui pull request #311
Opened 2021-03-18 13:20 UTC by AntonNazarenko

ASANA ticket: https://app.asana.com/0/1125859137800433/1200061962500088/f

📝 PR Description:
This PR adds the auto-login ability to any user who runs the app in a browser.
It can be enabled and disabled either on the login screen or on the settings page.
Also, it reduces the complexity of the settings page by refactoring it.
Refactored and improved prop-types.
Refactored code in all files related to this feature to improve it readability.

🖥 UI Demonstration: 

🛠 DEV UI (Chrome browser)

🎥 Small loom-demo: https://www.loom.com/share/58bf322b70a84bbdb49814dc5395f34c
<img width="1792" alt="Снимок экрана 2021-03-18 в 15 06 06" src="https://user-images.githubusercontent.com/51406639/111630872-78e8dd00-87fb-11eb-81a4-34ba7f27a1cf.png">
<img width="1792" alt="Снимок экрана 2021-03-18 в 15 07 56" src="https://user-images.githubusercontent.com/51406639/111631134-bbaab500-87fb-11eb-9b1a-925efd219e2a.png">

🏭 PRODUCTION UI (Electron App, Mac OS)
<img width="1792" alt="Снимок экрана 2021-03-18 в 15 06 36" src="https://user-images.githubusercontent.com/51406639/111630950-8b631680-87fb-11eb-9fb2-120bc023e5a7.png">
<img width="1792" alt="Снимок экрана 2021-03-18 в 15 08 28" src="https://user-images.githubusercontent.com/51406639/111631204-ce24ee80-87fb-11eb-9fde-5acebddc79cb.png">

2021-03-18 16:28 UTC, alexstotsky approved these changes
lgtm

2021-03-19 06:04 UTC, bhoomij requested changes
great job!! please see comment for state vars

2021-03-19 06:04 UTC, bhoomij commented on src/pages/Settings/Settings.js
> +      AUTOLOGIN_STATE: getAutoLoginState(),
same here, could use isDevEnv/AUTOLOGIN_STATE without state vars

2021-03-19 08:52 UTC, bhoomij approved these changes

2021-03-22 10:32 UTC, robertkowalski commented
<img width="493" alt="Screenshot 2021-03-22 at 11 29 07" src="https://user-images.githubusercontent.com/298166/111976453-eea5bf00-8b01-11eb-8f83-47f08af41f4c.png">

how do i use that? can't select the checkbox

is that visible to users? that would mean in prod users will use dev features? shouldn't it be hidden for users in prod?

another problem that comes with it: users will use it at some point out of laziness, and all the security is gone

2021-03-22 10:34 UTC, merged