(feature) Integrate ufx OrderHistory
bitfinexcom/bfx-hf-ui pull request #350
Opened 2021-04-14 16:41 UTC by JasonMHasperhoven

2021-04-14 17:06 UTC, JasonMHasperhoven commented
Review but do not merge yet! because we need a new tag of ufx-ui that includes the updated OrderHistory component.

2021-04-15 07:08 UTC, bhoomij requested changes
looks good to me, minor comment

2021-04-15 07:08 UTC, bhoomij commented on src/components/OrderHistory/OrderHistory.js
> +        columns={columns}
we can hide column with hidden prop in rowMapping, so I think columns prop is needed

2021-04-15 09:37 UTC, alexstotsky approved these changes

2021-04-15 17:09 UTC, bhoomij approved these changes

2021-04-26 07:51 UTC, merged