added helper for resetting default & max leverage value
bitfinexcom/bfx-hf-ui pull request #354
Opened 2021-04-16 11:57 UTC by Blaumaus

ASANA Ticket: [UI: Feature: AMPF0 max leverage should be x20](https://app.asana.com/0/1125859137800433/1198951310260685/f)

UI Demonstration:
![Screenshot from 2021-04-16 14-56-46](https://user-images.githubusercontent.com/35810911/115020966-ddef2b80-9eaa-11eb-8316-e0e75a400f9d.png)
![Screenshot from 2021-04-16 14-56-56](https://user-images.githubusercontent.com/35810911/115020969-df205880-9eaa-11eb-938d-72d4482c3ff6.png)

2021-04-16 12:15 UTC, bhoomij requested changes

2021-04-16 12:15 UTC, bhoomij commented on src/components/OrderForm/OrderForm.helpers.js
> +        fields[field].default = 5
this should be static and should come from bitfinex api, mostly (https://api.bitfinex.com/v1/symbols_details) can check with ivan also for exact api we can use to retrieve such data

2021-04-16 12:15 UTC, bhoomij commented on src/components/OrderForm/OrderForm.helpers.js
> +  Object.keys(fields).forEach(field => {
can use lodash for loop iteration, _mapkeys or similar

2021-04-16 12:57 UTC, robertkowalski commented on src/components/OrderForm/OrderForm.helpers.js
> +        fields[field].default = 5
@avsek477 does return it in the available pairs list via websocket

see this PR: https://github.com/bitfinexcom/bfx-hf-server/pull/68

2021-04-16 13:00 UTC, robertkowalski commented on src/components/OrderForm/OrderForm.helpers.js
> +        fields[field].default = 5
but if possible, using the REST API directly is better, so the Orderform can run without bfx-hf-server :)

2021-04-26 12:01 UTC, alexstotsky approved these changes

2021-04-27 05:08 UTC, bhoomij approved these changes

2021-04-27 05:08 UTC, bhoomij approved these changes
looks good 👍

2021-04-29 16:03 UTC, merged