refactor: remove exchange/binance switches from whole codebase
bitfinexcom/bfx-hf-ui pull request #376
Opened 2021-04-30 13:06 UTC by Blaumaus

ASANA Ticket: [UI: refactor - remove exchange/binance switches from whole codebase](https://app.asana.com/0/1125859137800433/1198213973398167/f)

Description: This pull request removes all mentions/switches/etc. of exchanges. Removed all exID's (using 'bitfinex' by default when necessary).
Refactored several components & fixed their prop types.

UI Demonstration:
![bfx-hf](https://user-images.githubusercontent.com/35810911/116699251-e2403c00-a9b4-11eb-9ddf-baed94025678.png)

2021-04-30 14:30 UTC, alexstotsky commented on src/components/AtomicOrdersTablePanel/AtomicOrdersTablePanel.js
>    activeMarket: PropTypes.objectOf(
I think better be used `arrayOf ` here for more precision

2021-04-30 14:31 UTC, alexstotsky commented on src/components/Backtester/Backtester.js
> +  markets: PropTypes.array, // eslint-disable-line
same as above

2021-04-30 14:40 UTC, alexstotsky requested changes

2021-04-30 14:40 UTC, alexstotsky commented on src/components/ChartPanel/ChartPanel.js
> +    markets: PropTypes.array, // eslint-disable-line
same here

2021-04-30 14:40 UTC, alexstotsky commented on src/components/PositionsTablePanel/PositionsTablePanel.js
> +  positions: PropTypes.array, // eslint-disable-line
and here

2021-04-30 14:40 UTC, alexstotsky commented on src/ui/Icons/FavoriteIcon.props.js
>  }
All props-types better be moved to a related component for better linting

2021-05-03 07:48 UTC, alexstotsky approved these changes

2021-05-03 09:27 UTC, bhoomij approved these changes
looks good, minor comment

2021-05-06 11:47 UTC, merged