(Improvement) Notifications UI
bitfinexcom/bfx-hf-ui pull request #386
Opened 2021-05-07 13:46 UTC by JasonMHasperhoven

Changes:

- Removed grey borders
- Replaced `"x"` with symmetrical x html entity `&#10005;`
- Changed alignment to left
- Increased font-size of message
- Decreased font-size of timestamp and replaced white color with text-color var
- Changed background color to provide better contrast
- Added info icon

Before:

![image](https://user-images.githubusercontent.com/13964126/117458528-71bc9080-af5b-11eb-9e15-cca08f1a20f4.png)

![image](https://user-images.githubusercontent.com/13964126/117458509-6c5f4600-af5b-11eb-86a9-b84915df8da2.png)

After:

![image](https://user-images.githubusercontent.com/13964126/117458424-58b3df80-af5b-11eb-92ff-168e7ce295d9.png)
![image](https://user-images.githubusercontent.com/13964126/117458467-61a4b100-af5b-11eb-9b56-d49f900c4bea.png)

2021-05-07 14:40 UTC, Blaumaus requested changes
New notifications look awesome! Great job.

2021-05-07 14:40 UTC, Blaumaus commented on src/components/NotificationsSidebar/Notification.js
> +    console.log('TCL: Notification -> render -> status', status)
I suppose you forgot to remove this `console.log`

2021-05-07 15:00 UTC, alexstotsky approved these changes
Looks good :+1:

2021-05-07 16:35 UTC, Blaumaus approved these changes

2021-05-10 05:03 UTC, bhoomij approved these changes

2021-05-11 10:19 UTC, merged