(Improvement) Improve how favorites' breaks lines
bitfinexcom/bfx-hf-ui pull request #414
Opened 2021-05-25 12:19 UTC by JasonMHasperhoven

Before:
![image](https://user-images.githubusercontent.com/13964126/119496806-ec1b4c00-bd74-11eb-821e-7a692acfd80e.png)

After:
![image](https://user-images.githubusercontent.com/13964126/119496763-e160b700-bd74-11eb-9e33-69b1d5911219.png)

2021-05-25 12:52 UTC, Blaumaus requested changes
Great job, with some minor proposals.

2021-05-25 12:52 UTC, Blaumaus commented on src/components/FavoriteTradingPairs/index.js
> +  return [ccy, '/', quote].map(part => (
I think it's better to use lodash `_map` here as Bhoomi proposed some time ago

2021-05-25 12:52 UTC, Blaumaus commented on src/components/FavoriteTradingPairs/index.js
> +  const [ccy, quote] = pair.split('/')
Same as above: we should use lodash `_split`

2021-05-25 13:31 UTC, JasonMHasperhoven commented on src/components/FavoriteTradingPairs/index.js
> +  return [ccy, '/', quote].map(part => (
Done

2021-05-25 14:28 UTC, Blaumaus approved these changes

2021-05-26 04:06 UTC, bhoomij approved these changes

2021-05-26 10:40 UTC, merged