Fix/tickers
bitfinexcom/bfx-hf-ui pull request #455
Opened 2021-06-03 13:44 UTC by dmytroshch

2021-06-03 15:52 UTC, Blaumaus requested changes
Great job with some minor proposals 👍

2021-06-03 15:52 UTC, Blaumaus commented on src/components/ExchangeInfoBar/ExchangeInfoBar.container.js
> +import { MAIN_MODE } from '../../redux/reducers/ui'
we don't need this import
```suggestion
```

2021-06-03 15:52 UTC, Blaumaus commented on src/redux/sagas/ws/on_all_tickers_subscribe.js
> +    yield delay(UPDATE_RATES_INTERVAL_MS)
Do we really need a return in catch statement? I think it would be better to refactor the code into something like that:
```suggestion
    try {
      const { data } = yield axios.get(URL)
      yield put(WSActions.setTickersData(data))
    } catch (err) {
      debug('failed to fetch tickers rates: %s', err.message)
    }
    yield delay(UPDATE_RATES_INTERVAL_MS)
```

2021-06-03 16:29 UTC, Blaumaus approved these changes

2021-06-04 08:44 UTC, bhoomij requested changes
could you please explore if you can reuse ticker.saga and ticker.selections from ufx-ui ?
if that is possible we will need to maintain lesser code, and wont have duplicate logic, and get optimised reducer logic. 
please take reference of how we are using ufx-ui sagas,selectors of book/trades in hf-ui, looks like we can achieve same for tickers

2021-06-07 13:14 UTC, bhoomij approved these changes
please add ufx-ui PR here as `Prerequisites` in PR description, also update ufx-ui version once new npm version is published with ticker changes, thanks! @dmytroshch

2021-06-07 13:53 UTC, dmytroshch commented
https://github.com/bitfinexcom/ufx-ui/pull/49

2021-06-07 13:54 UTC, dmytroshch commented
https://github.com/bitfinexcom/ufx-ui/pull/49

2021-06-08 06:28 UTC, bhoomij approved these changes

2021-06-08 10:01 UTC, merged