(fix) Ticker font improvement & Tickerlist scroll height
bitfinexcom/bfx-hf-ui pull request #477
Opened 2021-06-09 14:58 UTC by JasonMHasperhoven

Context:
https://files.slack.com/files-pri/T045ARQGE-F023Y6MGW3H/image.png

Asana:
https://app.asana.com/0/1125859137800433/1200260622693080

After this PR:
![image](https://user-images.githubusercontent.com/13964126/121378709-7c03ed00-c954-11eb-841a-32a6c16c77be.png)

2021-06-09 15:20 UTC, Blaumaus approved these changes

2021-06-09 17:36 UTC, bhoomij requested changes

2021-06-09 17:36 UTC, bhoomij commented on src/components/ExchangeInfoBar/ExchangeInfoBar.js
> +          style={size.height ? { height: `calc(100% - ${size.height}px)` } : undefined}
when I tested this PR, found that even after removing style/tickerRef related changes, and only setting height: 100% for .hfui-exchangeinfobar__tickerlist-wrapper, it solves scroll height issue

could you please check if same works without being size/height aware? let me know if I am missing any case

2021-06-10 08:11 UTC, JasonMHasperhoven commented on src/components/ExchangeInfoBar/ExchangeInfoBar.js
> +          style={size.height ? { height: `calc(100% - ${size.height}px)` } : undefined}
Let me check

2021-06-10 12:20 UTC, JasonMHasperhoven commented on src/components/ExchangeInfoBar/ExchangeInfoBar.js
> +          style={size.height ? { height: `calc(100% - ${size.height}px)` } : undefined}
Height 100% will make it exceed the wrapper (see the scrollbar also being cut off)
![image](https://user-images.githubusercontent.com/13964126/121523831-b4183800-ca07-11eb-8e56-fade4fd2d499.png)

2021-06-10 12:22 UTC, JasonMHasperhoven commented on src/components/ExchangeInfoBar/ExchangeInfoBar.js
> +          style={size.height ? { height: `calc(100% - ${size.height}px)` } : undefined}
I know it's complicated logic, that's partly because it's inside a flexible height (because it part of the grid) and I tried to do it using only flex with flex-grow: 1 to fill up the space, but then it needs to be capped to a max-height too. This way with calc seems to work, but if you know of a simpler way let me know.

2021-06-11 08:06 UTC, bhoomij approved these changes

2021-06-23 10:02 UTC, merged