improvement: Tickers: showing volume in USD for non-paper pairs
bitfinexcom/bfx-hf-ui pull request #487
Opened 2021-06-14 12:41 UTC by dmytroshch

ticket - https://app.asana.com/0/1200372033300327/1200434110231994

Showing volume in USD for non-paper pairs. Need to update bfx-ui/containers for using some selectors and fn

for main mode
![Снимок экрана от 2021-06-14 15-35-07](https://user-images.githubusercontent.com/81973123/121893675-ef2bab80-cd26-11eb-96d3-a94a7dbcc19d.png)

for paper mode
![Снимок экрана от 2021-06-14 15-41-15](https://user-images.githubusercontent.com/81973123/121893754-05396c00-cd27-11eb-8c9b-d19dc23137a3.png)

2021-06-15 05:26 UTC, bhoomij requested changes

2021-06-15 05:26 UTC, bhoomij commented on src/components/ExchangeInfoBar/ExchangeInfoBar.js
> +            }}
please declare it outside class, to avoid passing new object reference on every render

2021-06-15 13:41 UTC, Blaumaus approved these changes

2021-06-16 18:56 UTC, bhoomij approved these changes

2021-06-17 08:42 UTC, dmytroshch commented
need bfx-containers updating

2021-06-17 14:28 UTC, bhoomij approved these changes

2021-06-23 11:23 UTC, merged