improvement: OrderForm: added hepling messages for checkboxes
bitfinexcom/bfx-hf-ui pull request #523
Opened 2021-07-01 13:17 UTC by dmytroshch

https://github.com/bitfinexcom/ufx-ui/pull/82

Now if user hover cursor to checkbox's placeholder in atomic orders form, it is showing helping information about current option, as it works on web
![Снимок экрана от 2021-07-01 14-57-05](https://user-images.githubusercontent.com/81973123/124130713-beb67200-da87-11eb-8d0a-d343bfb9d27f.png)
![Снимок экрана от 2021-07-01 15-03-53](https://user-images.githubusercontent.com/81973123/124130719-bfe79f00-da87-11eb-88ec-fe83ef05df66.png)

2021-07-01 13:23 UTC, Blaumaus requested changes
Good job with a minor proposal

2021-07-01 13:23 UTC, Blaumaus commented on src/util/ui.js
> +  const rez = _toString(x).replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ',')
why do we need these changes?

2021-07-01 13:24 UTC, dmytroshch commented on src/util/ui.js
> +  const rez = _toString(x).replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ',')
accidentally

2021-07-05 13:13 UTC, bhoomij approved these changes
looks good, please keep in DRAFT until relevant change in ufx-ui is published

2021-07-18 10:44 UTC, bhoomij approved these changes

2021-07-19 11:15 UTC, bhoomij requested changes
@dmytroshch I just noticed that we now have help cursor even for Checkbox that do not have tooltip-help (attached screencast, could you please fix it ? )


https://user-images.githubusercontent.com/29878604/126151864-fe9dc6ef-50b0-4b6b-b863-45c6b0fb93b0.mov

I think we should revert this change https://github.com/bitfinexcom/ufx-ui/pull/82/files#diff-ebc8b0fa9a1693f8d1722e21806e5c6cc59f919061d6cb056d7fc1bb6f782edcL61

2021-07-21 05:53 UTC, bhoomij approved these changes

2021-07-21 09:28 UTC, merged