App settings modal
bitfinexcom/bfx-hf-ui pull request #534
Opened 2021-07-06 11:48 UTC by JasonMHasperhoven

![image](https://user-images.githubusercontent.com/13964126/124594782-4679f300-de71-11eb-9e07-1f07cde802f1.png)

![image](https://user-images.githubusercontent.com/13964126/124594811-4f6ac480-de71-11eb-8a39-d701b1579cbc.png)

![image](https://user-images.githubusercontent.com/13964126/124594826-5396e200-de71-11eb-9e05-6b452133372d.png)

2021-07-06 22:19 UTC, Blaumaus requested changes
This new modal looks amazing! Good job with some minor proposals

2021-07-06 22:19 UTC, Blaumaus commented on src/components/AppSettingsModal/AppSettingsModal.js
> +
We should validate the prop types here.

```suggestion

AppSettingsModal.propTypes = {
  isOpen: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired,
}

```

2021-07-06 22:19 UTC, Blaumaus commented on src/components/AppSettingsModal/AppSettingsModal.js
> +/* eslint-disable react/prop-types */
Don't need this comment here anymore; added import for `PropTypes`

```suggestion
import React, { useState } from 'react'
import PropTypes from 'prop-types'
```

2021-07-06 22:19 UTC, Blaumaus commented on src/components/AppSettingsModal/AppSettingsModal.TradingMode.js
> +const TradingMode = ({ onClose }) => {
PropTypes here also should be validated to maintain codebase consistency

2021-07-07 07:53 UTC, bhoomij approved these changes
looking great 👍 

could you add asana task please ? so this is not missed from QA cycle

2021-07-07 10:27 UTC, robertkowalski commented
created https://app.asana.com/0/1125859137800433/1200571179851769

2021-07-07 10:27 UTC, merged