(improvement) Scroll bars
bitfinexcom/bfx-hf-ui pull request #545
Opened 2021-07-15 14:44 UTC by JasonMHasperhoven

Asana:
https://app.asana.com/0/1125859137800433/1199410469158999/f

Description:
Improve scrollbars for each panels

https://user-images.githubusercontent.com/13964126/125807674-aeb64037-0e13-45ab-89ee-9c2e2ca1965c.mov

2021-07-15 15:07 UTC, Blaumaus requested changes
works perfectly well on both firefox and chromium

2021-07-15 15:07 UTC, Blaumaus commented on src/index.js
> +import Scrollbars from './ui/Scrollbars'
this variable is not used anywhere

```suggestion
```

2021-07-15 15:45 UTC, dmytroshch commented on src/ui/Scrollbars/Scrollbars.js
> -export default memo(Scrollbars)
why did you removed memo wrapper of this component. we don't have local state there

2021-07-15 15:46 UTC, dmytroshch approved these changes

2021-07-15 15:46 UTC, dmytroshch commented
Great job!

2021-07-19 04:49 UTC, bhoomij approved these changes

2021-07-19 08:40 UTC, JasonMHasperhoven commented on src/ui/Scrollbars/Scrollbars.js
> -export default memo(Scrollbars)
I think it's not needed. Though I didn't test it, but I think if you wrap a component in memo it can be worse for performance if it doesnt have many props - which is the case here.

2021-07-21 09:32 UTC, merged