(improvement) Update Electron to v17
bitfinexcom/bfx-hf-ui pull request #645
Opened 2022-02-07 12:42 UTC by Blaumaus

ASANA Ticket: [Upgrade electron to the latest version](https://app.asana.com/0/1125859137800433/1201766611631274/f)

Changelog:
 - updated Electron to v17
 - (minor) updated other dependencies to latest version

UI Demonstration:
![Screenshot from 2022-02-07 14-38-15](https://user-images.githubusercontent.com/35810911/152790006-dd56827d-d18d-4527-85f1-e71274b4e047.png)

2022-02-07 12:54 UTC, tarcisiozf commented on package.json
>    ],
can we update the [engine](https://github.com/bitfinexcom/bfx-hf-ui/blob/master/package.json#L6) to `>=16`? Ref: https://www.electronjs.org/blog/electron-17-0#stack-changes

2022-02-08 10:35 UTC, bhoomij requested changes

2022-02-08 10:35 UTC, bhoomij commented on .github/workflows/pull_request.yml
> +        node-version: [16.x]
lets set this to node 14 as electron build server only supports node 14.x (https://bitfinex.slack.com/archives/C02UVLC5ZD0/p1644227918521639?thread_ts=1643914764.588169&cid=C02UVLC5ZD0)

2022-02-08 10:35 UTC, bhoomij commented on package.json
> +    "node": ">=16"
^ node 14

2022-02-09 05:53 UTC, bhoomij commented
@Blaumaus could you share macos binaries either here or via slack ? just want to try and make sure electron 17 works with node 14 too!

2022-02-11 16:59 UTC, tarcisiozf requested changes

2022-02-11 16:59 UTC, tarcisiozf commented on package.json
> +    "node": ">=14"
please change the version on the [.tool-versions](https://github.com/bitfinexcom/bfx-hf-ui/blob/master/.tool-versions)

2022-02-14 12:41 UTC, bhoomij commented
FYI: I am facing issue on macOS with this PR, holding merge until I could spent more time debug and fix for mac

2022-03-03 12:39 UTC, closed without merging