(improvement) Using .env instead of setting variables in the package.json
bitfinexcom/bfx-hf-ui pull request #796
Opened 2023-02-14 23:30 UTC by Blaumaus

ASANA Ticket: [Cleanup Move env vars out of build/start script](https://app.asana.com/0/1201848935859401/1203020791627955/f)

<img width="1440" alt="Screenshot 2023-02-14 at 23 30 17" src="https://user-images.githubusercontent.com/35810911/218886459-54be798e-4993-4b43-a704-dd4f95472979.png">
(the app is running based on the vars set in the .env file of the bfx-hf-ui repo)

2023-02-15 10:07 UTC, bhoomij requested changes

2023-02-15 10:07 UTC, bhoomij commented on .env.example
> +REACT_APP_CHART_URL=https://hchart.bitfinex.com/v0
these envs are needed only for hosted web app. 
lets remove them to avoid further ambiguity as this env file is only for electron app

2023-02-15 18:53 UTC, bhoomij commented on package.json
> +    "start": "cd ./bfx-hf-ui-core && cross-env REACT_APP_DEV=1 env-cmd -f ../.env node scripts/start.js",
`env-cmd -f ../.env`

@Blaumaus QQ, 
wouldn't it expect .env file outside of project folder? 
If that is case, we should put .env file inside bfx-hf-ui so it dont break build current script on production server
or let me know if I am missing something in how the command works

2023-02-15 20:34 UTC, Blaumaus commented on package.json
> +    "start": "cd ./bfx-hf-ui-core && cross-env REACT_APP_DEV=1 env-cmd -f ../.env node scripts/start.js",
I put this `../.env` file because we do `cd ./bfx-hf-ui-core` and by default env-cmd expects a `.env` file in that folder.

2023-02-16 04:27 UTC, bhoomij commented on package.json
> +    "start": "cd ./bfx-hf-ui-core && cross-env REACT_APP_DEV=1 env-cmd -f ../.env node scripts/start.js",
okay, then do we have .env in bfx-hf-ui ? I see we only committing .env.example in this PR. 
As we have only url routes and not any confidential data, I think we can commit .env too so dont have to modify build scripts, wdyt ?

2023-02-16 04:36 UTC, bhoomij commented on package.json
> +    "start": "cd ./bfx-hf-ui-core && cross-env REACT_APP_DEV=1 env-cmd -f ../.env node scripts/start.js",
found it fails CI checks/build because of same error I suspected ..

<img width="1688" alt="Screenshot 2023-02-16 at 10 05 08 AM" src="https://user-images.githubusercontent.com/29878604/219269564-42901f8d-f92d-495e-ad33-bc3029b12ad5.png">

2023-02-17 16:41 UTC, Blaumaus commented on package.json
> +    "start": "cd ./bfx-hf-ui-core && cross-env REACT_APP_DEV=1 env-cmd -f ../.env node scripts/start.js",
yep, my bad, it's a habit to hide `.env` files in `.gitignore`. the CI should work fine now.

2023-02-20 09:27 UTC, bhoomij approved these changes

2023-02-20 09:27 UTC, merged