(fix) Autoupdate on MacOS
bitfinexcom/bfx-hf-ui pull request #839
Opened 2023-07-31 13:58 UTC by dmytroshch

ticket - https://app.asana.com/0/1201849173362898/1205172768485798
reverted https://github.com/bitfinexcom/bfx-hf-ui/commit/6be6d62667b78e5ee7631f2c43366c48fccf9357

2023-07-31 14:18 UTC, tarcisiozf requested changes

2023-07-31 14:18 UTC, tarcisiozf commented on scripts/auto-updater/bfx.mac.updater.js
> +          defaultDirMode: '0o777',
not a good practice to use `777`, maybe `744` is better in this case

2023-07-31 14:19 UTC, dmytroshch commented on scripts/auto-updater/bfx.mac.updater.js
> +          defaultDirMode: '0o777',
that is prev version of the file

2023-07-31 14:19 UTC, dmytroshch commented on scripts/auto-updater/bfx.mac.updater.js
> +          defaultDirMode: '0o777',
we could try, then test it

2023-08-18 09:33 UTC, bhoomij approved these changes

2023-08-18 09:33 UTC, merged